### ISSUE TITLE
Mettre a jour le compteur des questions au fur et a mesure

### ISSUE THREAD

**Issue by lmag** [Evarisk/DigiQuali#1587]
![image](https://github.com/Evarisk/DigiQuali/assets/3288514/bd3ed57d-72cb-4601-955c-3f7e77d5363b)

La mise à jour du compteur n est pas faite

**Comment by eoxia-amandine** [comment]
Proposition V1 de nouvel agencement :

V**ersion ordinateur (état activé)**
![controle-etat-reponse-1](https://github.com/Evarisk/DigiQuali/assets/18576747/ff21c5d8-4d8c-4bad-9fc8-b206c5e0a699)

**Version ordinateur (état désactivé)**
![controle-etat-reponse-desactive-1](https://github.com/Evarisk/DigiQuali/assets/18576747/d9eedd3f-c8a0-4893-a3f5-1b71201a95

**Version mobile (état activé)**
![controle-etat-reponse-mobile-1](https://github.com/Evarisk/DigiQuali/assets/18576747/472333ed-4c27-4255-b64b-b83feb38bf3d)
4e)

**Comment by eoxia-amandine** [comment]
Proposition V3 sans le titre

Desktop
![controle-etat-reponse-3](https://github.com/Evarisk/DigiQuali/assets/18576747/475f13d5-c8ad-4291-b838-3c2f8c6cc719)

Mobile 
![controle-etat-reponse-mobile-3](https://github.com/Evarisk/DigiQuali/assets/18576747/e6fef642-cbdd-4f9e-9fb7-5a6cbdb26d9d)

**Comment by eoxia-amandine** [comment]
Proposition V4 :
- Ajout du pourcentage d'avancement
- Légère amélioration graphique de la progress bar

Desktop 
![controle-etat-reponse-4](https://github.com/Evarisk/DigiQuali/assets/18576747/d3e5168c-e992-404a-89c0-8132eb5fd9e1)

Mobile
![controle-etat-reponse-mobile-4](https://github.com/Evarisk/DigiQuali/assets/18576747/c48a868a-3a05-4e88-948f-3aa761a784e2)
