### ISSUE TITLE
IHM - Choix du controle sur les TAGs

### ISSUE THREAD

**Issue by lmag** [Evarisk/DigiQuali#1614]
Faire une interface de choix des contrôles basé sur les TAgs classiques

- [x] Avec les choix sur les Tags
- [x] Avec une liste déroulante

Exemple choix sur les TAGs

![Image](https://github.com/Evarisk/DigiQuali/assets/3288514/2e5e7d6f-c925-43e0-bec6-43ac710c393b)

**Comment by nicolas-eoxia** [comment]
Besoin de faire du CSS @eoxia-amandine

**Comment by eoxia-amandine** [comment]
Corriger la grille en CSS : 
- Voir pour ajouter une classe "no-responsive" qui ne touche pas à une grille en mobile ?

**Comment by nicolas-eoxia** [comment]
Il me faut les assets de la maquette @MartinHennes

**Comment by lmag** [comment]
@nicolas-eoxia https://github.com/Evarisk/DigiQuali/issues/1658

**Comment by lmag** [comment]
![image](https://github.com/Evarisk/DigiQuali/assets/3288514/3e2e0e9d-4bc4-4222-bf17-90bb16305a28)
