### ISSUE TITLE
Catégorie par défaut : contrôle

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/DigiQuali#1658]
Gestion des catégories comme sur digirisk pour la fiche modèle
manque les pictos

**Comment by lmag** [comment]
- Qualité (<i class="fa-regular fa-pen-to-square"></i>)
- Hygiène-Sécurité 
- Matériels (<i class="fa-solid fa-screwdriver-wrench"></i>)
- Véhicules (<i class="fa-solid fa-car-side"></i>)
--
