### ISSUE TITLE
IHM - Front End simplification de l'interface de réponse avec des images, smileys

### ISSUE THREAD

**Issue by lmag** [Evarisk/DigiQuali#1734]
MEttre en place des smileys
![image](https://github.com/Evarisk/DigiQuali/assets/3288514/cd9fc989-988f-4237-a45e-f5302057bb9f)

**Comment by evarisk-charles** [comment]
Un système d'emoji fonctionnant de cette manière 
![image](https://github.com/Evarisk/DigiQuali/assets/158461084/22455717-980e-4873-9fca-be4037dc0c5f) ?

**Comment by lmag** [comment]
![image](https://github.com/Evarisk/DigiQuali/assets/3288514/be289603-65cc-4e0d-979e-2967130eb577)
