### ISSUE TITLE
Problème Tag Contrôle sur téléphone

### ISSUE THREAD

**Issue by titicopac** [Evarisk/DigiQuali#1741]
Dans la catégorie TAG, la liste déroulante ne s’affiche pas sur le support téléphone comme tu peux le voir sr la photo ci-dessous.
![fff](https://github.com/Evarisk/DigiQuali/assets/100367004/d58b6666-9ff6-432e-88a2-41c91ca7bfee)

**Comment by nicolas-eoxia** [comment]
Bonjour, @titicopac 

Merci de votre participation

Cette issue sera corrigé dans la version 1.11.0
Voici le commit de correction : https://github.com/Evarisk/DigiQuali/pull/1743

Bonne journée,

Nicolas
