### ISSUE TITLE
Erreur clonage modèle

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/DigiQuali#1806]
Je clone ce jour un modèle de contrôle et il me reprend :

La date de création du modèle cloné
Ainsi que l’incrément du modèle cloné
 

Je pensais que ce serait => MO2404-XXXX

![Image](https://github.com/Evarisk/DigiQuali/assets/52404047/b9bc0bad-df50-48a8-a897-878c1c7739bd)

**Comment by evarisk-francois** [comment]
La date de création lors du clonage devrait être `.now()` plutôt que la date de création du modèle original, non ? Actuellement, c'est celle du modèle original.
