### ISSUE TITLE
Bug - PHP Fatal error

### ISSUE THREAD

**Issue by ribrahime** [Evarisk/DigiQuali#1884]
Bonjour,

Suite à l'installation de Digiquali 1.12.0, en cliquant soit sur Question, Modèle, Contrôle, Questionnaire ou Outils  j'obtiens une "erreur 500".
notre configuration : saturne 1.6.0 et Dolibarr 19.0.2. 

Voici l'erreur retournait par les logs par exemple quand on a cliqué sur Question :
{"@type":"error_log","@app":"digirisk","message":"PHP Fatal error:  Type of Question::$isextrafieldmanaged must not be defined (as in class SaturneObject) in /var/www/html/custom/digiquali/class/question.class.php on line 30","level":"error"}

Cordialement

**Comment by lmag** [comment]
Merci @ribrahime Merci pour cette première remontée on vous fait un retour rapide

**Comment by nicolas-eoxia** [comment]
Bonjour, @ribrahime 

Merci de votre participation

Cette issue sera corrigé dans la version 1.13
Voici le lien vers le suivi de l'issue : (https://github.com/Evarisk/DigiQuali/commit/5b8bbeacffad14572416097322e380b0519b7757)

Bonne journée,

Nicolas

**Comment by ribrahime** [comment]
Bonjour @nicolas-eoxia 

Est-ce que vous savez quand la version 1.13 sera disponible ?

Bonne journée,

Rayan

**Comment by lmag** [comment]
Bonjour, @ribrahime ,
Nous n'avons pas de planification pour la sortie des releases. Le problème est réglé, la solution est disponible. Je vous encourage à regarder le suivi
Bien cordialement
