### ISSUE TITLE
[IHM]-Mettre à jour le lien et ranger les médias et les fonctions

### ISSUE THREAD

**Issue by lmag** [Evarisk/DigiQuali#221]
![image](https://user-images.githubusercontent.com/3288514/156620205-4e161ab8-a8fc-4a6f-bdaa-714e9bce4593.png)
- ADD médias = fonction
- Unlink médias = fonction
- Grossir l'image = loupe
- Affichage médias liés = fonction listing des médias

**Comment by eoxia-amandine** [comment]
![question-controle-2](https://user-images.githubusercontent.com/18576747/156774125-07bb6378-e91b-4677-ae8d-96b995f46437.png)

**Comment by Alexandra-copac** [comment]
Je vote pour le choix 1

**Comment by titicopac** [comment]
je vote pour le choix 1

**Comment by titicopac** [comment]
Saïd vote pour le choix 1 aussi.

**Comment by lmag** [comment]
OK Choix 1 validé

**Comment by lmag** [comment]
Identifier les questions qui ont une réponse
![image](https://user-images.githubusercontent.com/3288514/165768270-6fc98f48-a865-413d-8e0a-7d6f64662ff3.png)
?

**Comment by lmag** [comment]
Réduire le tour des photos et mettre un fond de couleur
